DROP TABLE TEAM CASCADE CONSTRAINT;
DROP TABLE DRIVER CASCADE CONSTRAINT;

CREATE TABLE TEAM (
    TEAM_ID VARCHAR2(20),
    NAMEX VARCHAR2(20) NOT NULL,
    BUDGET FLOAT, 
    CONSTRAINT BUDGET_CHECK CHECK (BUDGET >= 0.00)
); 
CREATE TABLE DRIVER(
    DRIVER_NO VARCHAR2(20), 
    DRIVER_NAME VARCHAR2(20) NOT NULL, 
    DRIVER_CITY VARCHAR2(20), 
    CONSTRAINT DRIVER_NAME_PK PRIMARY KEY (DRIVER_NO) 
); 

INSERT INTO TEAM VALUES('1', 'Ferrari', 120000.00);
INSERT INTO TEAM VALUES('2', 'Redbull', 200000.50);
INSERT INTO TEAM VALUES('3', 'McLaren', 100000.00);
INSERT INTO TEAM VALUES('4', 'Mercedes', 930000.70);

INSERT INTO DRIVER VALUES('C-101', 'Max', 'Amsterdram'); 
INSERT INTO DRIVER VALUES('C-102', 'Piastri', 'Melbourne'); 
INSERT INTO DRIVER VALUES('C-103', 'Norris', 'Bristol'); 
INSERT INTO DRIVER VALUES('C-104', 'Leclerc', 'Monte Carlo'); 
INSERT INTO DRIVER VALUES('C-105', 'Hamilton', 'Bristol'); 


ALTER TABLE DRIVER ADD "DATE OF BIRTH" DATE;
ALTER TABLE DRIVER RENAME COLUMN "DRIVER_NO" TO DRIVER_ID;
ALTER TABLE TEAM ADD PRIMARY KEY (TEAM_ID);

SELECT NAMEX FROM TEAM WHERE BUDGET > (SELECT BUDGET FROM TEAM WHERE NAMEX = 'Ferrari');
SELECT DRIVER_NAME FROM DRIVER WHERE DRIVER_CITY != 'Bristol';
UPDATE TEAM SET BUDGET = BUDGET * 0.75 WHERE BUDGET > (SELECT BUDGET FROM TEAM WHERE NAMEX = 'McLaren');
UPDATE TEAM SET BUDGET = BUDGET - 20000.00 WHERE TEAM_ID = '3';
UPDATE TEAM SET BUDGET = BUDGET + 20000.00 WHERE TEAM_ID = '2';

DELETE FROM TEAM WHERE BUDGET < (SELECT BUDGET FROM TEAM WHERE TEAM_ID = '4');


-- Pending tasks: 

ALTER TABLE TEAM ADD DRIVER_ID VARCHAR2(20);
UPDATE TEAM SET DRIVER_ID = 'C-104' WHERE TEAM_ID = '1';
UPDATE TEAM SET DRIVER_ID = 'C-102, C-103' WHERE TEAM_ID = '3';
UPDATE TEAM SET DRIVER_ID = 'C-101' WHERE TEAM_ID = '2';
UPDATE TEAM SET DRIVER_ID = 'C-105' WHERE TEAM_ID = '4';


SELECT DRIVER_NAME 
FROM DRIVER 
WHERE DRIVER_ID IN (
    SELECT DRIVER_ID FROM TEAM WHERE BUDGET < 200000
);
