DROP TABLE Course CASCADE CONSTRAINTS;
DROP TABLE Instructor CASCADE CONSTRAINTS;

CREATE TABLE Instructor (
    I_ID INT PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    DEPT_NAME VARCHAR2(10),
    SALARY NUMBER(10, 2)
);

CREATE TABLE Course (
    COURSE_CODE VARCHAR2(10) PRIMARY KEY,
    I_ID INT NOT NULL,
    CREDIT NUMBER(3),
    CONSTRAINT FK_INSTRUCTOR FOREIGN KEY (I_ID) REFERENCES Instructor(I_ID)
);

INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (1001, 'Anas', 'CSE', 10000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (1002, 'Bananee', 'CSE', 12000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (1003, 'Fardin', 'CSE', 11500);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (2001, 'Sabit', 'EEE', 12000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (2002, 'Nadim', 'EEE', 14000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (1004, 'Ivan', 'CSE', 12000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (2004, 'Tashfiq', 'EEE', 15000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (3001, 'Aarav', 'MCE', 12500);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (3002, 'Ishani', 'MCE', 13000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (4001, 'Zayan', 'CEE', 13500);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (4002, 'Diya', 'CEE', 12800);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (5001, 'Arjun', 'BTM', 14000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (5002, 'Maya', 'BTM', 14500);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (6001, 'Riya', 'ARC', 15000);
INSERT INTO Instructor (I_ID, NAME, DEPT_NAME, SALARY) VALUES (6002, 'Kabir', 'ARC', 15500);


INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('CSE 4308', 1001, 2);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('CSE 4633', 1004, 3);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('MCE 5101', 3001, 4);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('MCE 5201', 3002, 3);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('CEE 4101', 4001, 3);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('CEE 4201', 4002, 2);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('BTM 3301', 5001, 5);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('BTM 3401', 5002, 4);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('ARC 6101', 6001, 3);
INSERT INTO Course (COURSE_CODE, I_ID, CREDIT) VALUES ('ARC 6201', 6002, 4);


DESC Instructor;
DESC Course;

SELECT * FROM Instructor;
SELECT * FROM Course;

SELECT I_ID, course_code 
FROM Instructor NATURAL JOIN course; 

SELECT * FROM Instructor ORDER BY SALARY ASC; 
SELECT * FROM Instructor ORDER BY SALARY DESC; 
SELECT * FROM Instructor ORDER BY SALARY ASC, DEPT_NAME DESC; 

UPDATE Instructor SET SALARY = 16000 WHERE SALARY = 10000; 
UPDATE Instructor SET SALARY = SALARY * 1.5 WHERE DEPT_NAME = 'CSE'; 


SELECT * FROM Instructor ORDER BY SALARY ASC; 
-- DELETE FROM Instructor WHERE DEPT_NAME = 'EEE';
SELECT * FROM Instructor;
SELECT DISTINCT SALARY FROM INSTRUCTOR; 
SELECT DISTINCT DEPT_NAME FROM INSTRUCTOR; 