DROP TABLE PUBLICATIONS;
DROP TABLE STUDENTS;
DROP TABLE PROJECTS;
DROP TABLE FACULTIES;
DROP TABLE RESEARCH_GROUP;

CREATE TABLE RESEARCH_GROUP (
    unique_name VARCHAR(50),
    lab VARCHAR(50),
    budget NUMERIC(12, 2),
    group_head VARCHAR(50),
    CONSTRAINT PK_RESEARCH_GROUP PRIMARY KEY (unique_name)
);

CREATE TABLE FACULTIES (
    Faculty_ID VARCHAR(10),
    Namex VARCHAR(50),
    Contact_Number VARCHAR(15),
    Research_Lab VARCHAR(50),
    CONSTRAINT PK_FACULTIES PRIMARY KEY (Faculty_ID),
    CONSTRAINT FK_FACULTIES_RESEARCH_LAB FOREIGN KEY (Research_Lab) REFERENCES RESEARCH_GROUP(unique_name)
);

CREATE TABLE STUDENTS (
    Student_ID VARCHAR(10),
    Namex VARCHAR(50),
    Contact_Number VARCHAR(15),
    Research_Lab VARCHAR(50),
    Supervisor_ID VARCHAR(10),
    Project_ID VARCHAR(10),
    CONSTRAINT PK_STUDENTS PRIMARY KEY (Student_ID),
    CONSTRAINT FK_STUDENTS_RESEARCH_LAB FOREIGN KEY (Research_Lab) REFERENCES RESEARCH_GROUP(unique_name),
    CONSTRAINT FK_STUDENTS_SUPERVISOR_ID FOREIGN KEY (Supervisor_ID) REFERENCES FACULTIES(Faculty_ID),
    CONSTRAINT FK_STUDENTS_PROJECT_ID FOREIGN KEY (Project_ID) REFERENCES PROJECTS(Project_ID)
);

CREATE TABLE PROJECTS (
    Project_ID VARCHAR(10),
    Project_Title VARCHAR(100),
    Starting_Date DATE,
    Ending_Estimated_Date DATE,
    Research_Area VARCHAR(50),
    Faculty_ID VARCHAR(10),
    CONSTRAINT PK_PROJECTS PRIMARY KEY (Project_ID),
    CONSTRAINT FK_PROJECTS_FACULTY_ID FOREIGN KEY (Faculty_ID) REFERENCES FACULTIES(Faculty_ID)
);

CREATE TABLE PUBLICATIONS (
    Title VARCHAR(100),
    Conference_Name VARCHAR(100),
    Publication_Date DATE,
    Research_Domain VARCHAR(50),
    Brief_Summary VARCHAR(100),
    Publisher_Faculty VARCHAR(10),
    Publisher_Student VARCHAR(10),
    CONSTRAINT PK_PUBLICATIONS PRIMARY KEY (Title),
    CONSTRAINT FK_PUBLICATIONS_PUBLISHER_FACULTY FOREIGN KEY (Publisher_Faculty) REFERENCES FACULTIES(Faculty_ID),
    CONSTRAINT FK_PUBLICATIONS_PUBLISHER_STUDENT FOREIGN KEY (Publisher_Student) REFERENCES STUDENTS(Student_ID)
);

DROP TABLE PUBLICATIONS;
DROP TABLE STUDENTS;
DROP TABLE PROJECTS;
DROP TABLE FACULTIES;
DROP TABLE RESEARCH_GROUP;
