DROP TABLE PERFORMS;
DROP TABLE INCLUDES;
DROP TABLE RATING;
DROP TABLE ARTIST;
DROP TABLE SONG;
DROP TABLE ALBUM;
DROP TABLE LISTENER;

CREATE TABLE ARTIST(
    ART_ID INTEGER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    GENDER VARCHAR2(10),
    CONSTRAINT pk_artist PRIMARY KEY(ART_ID)
);

CREATE TABLE ALBUM(
    ALB_ID INTEGER,
    TITLE VARCHAR2(60),
    RELEASE_YEAR VARCHAR2(20),
    LANGUAGE VARCHAR2(50),
    CONSTRAINT pk_album PRIMARY KEY(ALB_ID)
);

CREATE TABLE SONG(
    SONG_ID INTEGER,
    TITLE VARCHAR2(60),
    DURATION INTEGER,
    GENRE VARCHAR2(30),
    CONSTRAINT pk_song PRIMARY KEY(SONG_ID)
);

CREATE TABLE LISTENER(
    LIS_ID INTEGER,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    CONSTRAINT pk_listener PRIMARY KEY(LIS_ID)
);

CREATE TABLE PERFORMS(
    ART_ID INTEGER,
    SONG_ID INTEGER,
    CONSTRAINT pk_performs PRIMARY KEY(ART_ID, SONG_ID),
    CONSTRAINT fk_performs_artist FOREIGN KEY(ART_ID) REFERENCES ARTIST(ART_ID),
    CONSTRAINT fk_performs_song FOREIGN KEY(SONG_ID) REFERENCES SONG(SONG_ID)
);

CREATE TABLE INCLUDES(
    ALB_ID INTEGER,
    SONG_ID INTEGER,
    CONSTRAINT pk_includes PRIMARY KEY(ALB_ID, SONG_ID),
    CONSTRAINT fk_includes_album FOREIGN KEY(ALB_ID) REFERENCES ALBUM(ALB_ID),
    CONSTRAINT fk_includes_song FOREIGN KEY(SONG_ID) REFERENCES SONG(SONG_ID)
);

CREATE TABLE RATING(
    SONG_ID INTEGER,
    LIS_ID INTEGER,
    RATING FLOAT,
    CONSTRAINT pk_rating PRIMARY KEY(SONG_ID, LIS_ID),
    CONSTRAINT fk_rating_song FOREIGN KEY(SONG_ID) REFERENCES SONG(SONG_ID),
    CONSTRAINT fk_rating_listener FOREIGN KEY(LIS_ID) REFERENCES LISTENER(LIS_ID)
);

INSERT INTO ARTIST VALUES(1, 'Taylor', 'Swift', 'Female');
INSERT INTO ARTIST VALUES(2, 'Ed', 'Sheeran', 'Male');
INSERT INTO ARTIST VALUES(3, 'Beyonce', 'Knowles', 'Female');
INSERT INTO ARTIST VALUES(4, 'Bruno', 'Mars', 'Male');
INSERT INTO ARTIST VALUES(5, 'Adele', 'Adkins', 'Female');
INSERT INTO ARTIST VALUES(6, 'Justin', 'Timberlake', 'Male');
INSERT INTO ARTIST VALUES(7, 'Katy', 'Perry', 'Female');
INSERT INTO ARTIST VALUES(8, 'Rihanna', 'Fenty', 'Female');
INSERT INTO ARTIST VALUES(9, 'Drake', '', 'Male');
INSERT INTO ARTIST VALUES(10, 'Lady', 'Gaga', 'Female');
INSERT INTO ARTIST VALUES(11, 'Sam', 'Smith', 'Male');
INSERT INTO ARTIST VALUES(12, 'Shawn', 'Mendes', 'Male');
INSERT INTO ARTIST VALUES(13, 'Billie', 'Eilish', 'Female');
INSERT INTO ARTIST VALUES(14, 'Ariana', 'Grande', 'Female');
INSERT INTO ARTIST VALUES(15, 'Khalid', '', 'Male');
INSERT INTO ARTIST VALUES(16, 'The', 'Weeknd', 'Male');
INSERT INTO ARTIST VALUES(17, 'Selena', 'Gomez', 'Female');
INSERT INTO ARTIST VALUES(18, 'Maroon', '5', 'Male');
INSERT INTO ARTIST VALUES(19, 'Dua', 'Lipa', 'Female');
INSERT INTO ARTIST VALUES(20, 'Post', 'Malone', 'Male');
INSERT INTO ARTIST VALUES(21, 'Harry', 'Styles', 'Male');
INSERT INTO ARTIST VALUES(22, 'Mark', 'Ronson', 'Male');
INSERT INTO ARTIST VALUES(23, 'Cardi', 'B', 'Female');
INSERT INTO ARTIST VALUES(24, 'Justin', 'Bieber', 'Male');

INSERT INTO ALBUM VALUES(1, '1989', '2014', 'English');
INSERT INTO ALBUM VALUES(2, 'Divide', '2017', 'English');
INSERT INTO ALBUM VALUES(3, 'Lemonade', '2016', 'English');
INSERT INTO ALBUM VALUES(4, '24K Magic', '2016', 'English');
INSERT INTO ALBUM VALUES(5, '25', '2015', 'English');
INSERT INTO ALBUM VALUES(6, 'Purpose', '2015', 'English');
INSERT INTO ALBUM VALUES(7, 'Witness', '2017', 'English');
INSERT INTO ALBUM VALUES(8, 'Anti', '2016', 'English');
INSERT INTO ALBUM VALUES(9, 'Scorpion', '2018', 'English');
INSERT INTO ALBUM VALUES(10, 'Joanne', '2016', 'English');
INSERT INTO ALBUM VALUES(11, 'In The Lonely Hour', '2014', 'English');
INSERT INTO ALBUM VALUES(12, 'Shawn Mendes', '2018', 'English');
INSERT INTO ALBUM VALUES(13, 'When We All Fall Asleep, Where Do We Go?', '2019', 'English');
INSERT INTO ALBUM VALUES(14, 'Thank U, Next', '2019', 'English');
INSERT INTO ALBUM VALUES(15, 'Free Spirit', '2019', 'English');
INSERT INTO ALBUM VALUES(16, 'After Hours', '2020', 'English');
INSERT INTO ALBUM VALUES(17, 'Rare', '2020', 'English');
INSERT INTO ALBUM VALUES(18, 'Red Pill Blues', '2017', 'English');
INSERT INTO ALBUM VALUES(19, 'Future Nostalgia', '2020', 'English');
INSERT INTO ALBUM VALUES(20, 'Hollywood''s Bleeding', '2019', 'English');

INSERT INTO SONG VALUES(1, 'Shake It Off', 242, 'Pop');
INSERT INTO SONG VALUES(2, 'Thinking Out Loud', 281, 'Pop');
INSERT INTO SONG VALUES(3, 'Formation', 215, 'RNB');
INSERT INTO SONG VALUES(4, 'Uptown Funk', 269, 'Funk');
INSERT INTO SONG VALUES(5, 'Hello', 295, 'Soul');
INSERT INTO SONG VALUES(6, 'Can''t Stop the Feeling!', 236, 'Pop');
INSERT INTO SONG VALUES(7, 'Roar', 221, 'Pop');
INSERT INTO SONG VALUES(8, 'Work', 219, 'Dancehall');
INSERT INTO SONG VALUES(9, 'God''s Plan', 198, 'Hip-Hop');
INSERT INTO SONG VALUES(10, 'Bad Romance', 295, 'Pop');
INSERT INTO SONG VALUES(11, 'Stay With Me', 172, 'Soul');
INSERT INTO SONG VALUES(12, 'Stitches', 207, 'Pop');
INSERT INTO SONG VALUES(13, 'Bad Guy', 194, 'Pop');
INSERT INTO SONG VALUES(14, '7 Rings', 179, 'RNB');
INSERT INTO SONG VALUES(15, 'Young Dumb N Broke', 203, 'RNB');
INSERT INTO SONG VALUES(16, 'Blinding Lights', 200, 'Synth-pop');
INSERT INTO SONG VALUES(17, 'Lose You To Love Me', 206, 'Pop');
INSERT INTO SONG VALUES(18, 'Girls Like You', 235, 'Pop');
INSERT INTO SONG VALUES(19, 'Don''t Start Now', 183, 'Disco');
INSERT INTO SONG VALUES(20, 'Circles', 215, 'Pop');

INSERT INTO LISTENER VALUES(1, 'John', 'Doe');
INSERT INTO LISTENER VALUES(2, 'Jane', 'Smith');
INSERT INTO LISTENER VALUES(3, 'Emily', 'Johnson');
INSERT INTO LISTENER VALUES(4, 'Michael', 'Brown');
INSERT INTO LISTENER VALUES(5, 'Sarah', 'Davis');
INSERT INTO LISTENER VALUES(6, 'David', 'Miller');
INSERT INTO LISTENER VALUES(7, 'Laura', 'Wilson');
INSERT INTO LISTENER VALUES(8, 'Robert', 'Moore');
INSERT INTO LISTENER VALUES(9, 'Linda', 'Taylor');
INSERT INTO LISTENER VALUES(10, 'James', 'Anderson');
INSERT INTO LISTENER VALUES(11, 'Patricia', 'Thomas');
INSERT INTO LISTENER VALUES(12, 'Christopher', 'Jackson');
INSERT INTO LISTENER VALUES(13, 'Barbara', 'White');
INSERT INTO LISTENER VALUES(14, 'Daniel', 'Harris');
INSERT INTO LISTENER VALUES(15, 'Elizabeth', 'Martin');
INSERT INTO LISTENER VALUES(16, 'Matthew', 'Thompson');
INSERT INTO LISTENER VALUES(17, 'Jennifer', 'Garcia');
INSERT INTO LISTENER VALUES(18, 'Anthony', 'Martinez');
INSERT INTO LISTENER VALUES(19, 'Susan', 'Robinson');
INSERT INTO LISTENER VALUES(20, 'Andrew', 'Clark');

INSERT INTO PERFORMS VALUES(1, 1);
INSERT INTO PERFORMS VALUES(2, 2);
INSERT INTO PERFORMS VALUES(3, 3);
INSERT INTO PERFORMS VALUES(4, 4);
INSERT INTO PERFORMS VALUES(22, 4);
INSERT INTO PERFORMS VALUES(5, 5);
INSERT INTO PERFORMS VALUES(6, 6);
INSERT INTO PERFORMS VALUES(7, 7);
INSERT INTO PERFORMS VALUES(8, 8);
INSERT INTO PERFORMS VALUES(9, 9);
INSERT INTO PERFORMS VALUES(10, 10);
INSERT INTO PERFORMS VALUES(11, 11);
INSERT INTO PERFORMS VALUES(12, 12);
INSERT INTO PERFORMS VALUES(13, 13);
INSERT INTO PERFORMS VALUES(24, 13);
INSERT INTO PERFORMS VALUES(14, 14);
INSERT INTO PERFORMS VALUES(15, 15);
INSERT INTO PERFORMS VALUES(16, 16);
INSERT INTO PERFORMS VALUES(17, 17);
INSERT INTO PERFORMS VALUES(18, 18);
INSERT INTO PERFORMS VALUES(23, 18);
INSERT INTO PERFORMS VALUES(19, 19);
INSERT INTO PERFORMS VALUES(20, 20);

INSERT INTO INCLUDES VALUES(1, 1);
INSERT INTO INCLUDES VALUES(2, 2);
INSERT INTO INCLUDES VALUES(3, 3);
INSERT INTO INCLUDES VALUES(4, 4);
INSERT INTO INCLUDES VALUES(5, 5);
INSERT INTO INCLUDES VALUES(7, 7);
INSERT INTO INCLUDES VALUES(8, 8);
INSERT INTO INCLUDES VALUES(9, 9);
INSERT INTO INCLUDES VALUES(10, 10);
INSERT INTO INCLUDES VALUES(11, 11);
INSERT INTO INCLUDES VALUES(12, 12);
INSERT INTO INCLUDES VALUES(13, 13);
INSERT INTO INCLUDES VALUES(14, 14);
INSERT INTO INCLUDES VALUES(15, 15);
INSERT INTO INCLUDES VALUES(16, 16);
INSERT INTO INCLUDES VALUES(17, 17);
INSERT INTO INCLUDES VALUES(18, 18);
INSERT INTO INCLUDES VALUES(19, 19);
INSERT INTO INCLUDES VALUES(20, 20);

INSERT INTO RATING VALUES(1, 1, 4.5);
INSERT INTO RATING VALUES(2, 2, 4.7);
INSERT INTO RATING VALUES(3, 3, 4.2);
INSERT INTO RATING VALUES(4, 4, 3.9);
INSERT INTO RATING VALUES(5, 5, 4.8);
INSERT INTO RATING VALUES(6, 6, 4.0);
INSERT INTO RATING VALUES(7, 7, 3.5);
INSERT INTO RATING VALUES(8, 8, 4.1);
INSERT INTO RATING VALUES(9, 9, 4.3);
INSERT INTO RATING VALUES(10, 10, 4.6);
INSERT INTO RATING VALUES(11, 11, 4.4);
INSERT INTO RATING VALUES(12, 12, 4.2);
INSERT INTO RATING VALUES(13, 13, 4.9);
INSERT INTO RATING VALUES(14, 14, 4.0);
INSERT INTO RATING VALUES(15, 15, 4.1);
INSERT INTO RATING VALUES(16, 16, 4.8);
INSERT INTO RATING VALUES(17, 17, 4.3);
INSERT INTO RATING VALUES(18, 18, 4.7);
INSERT INTO RATING VALUES(19, 19, 4.6);
INSERT INTO RATING VALUES(20, 20, 4.5);
INSERT INTO RATING VALUES(13, 1, 4.8);
INSERT INTO RATING VALUES(5, 2, 4.9);
INSERT INTO RATING VALUES(1, 3, 4.6);
INSERT INTO RATING VALUES(16, 4, 4.8);
INSERT INTO RATING VALUES(16, 5, 4.7); 
