DROP TABLE STUDENT CASCADE CONSTRAINTS; 
CREATE TABLE STUDENT (
        ID NUMBER, 
        NAMEX VARCHAR2(50) NOT NULL, 
        DEPT_NAME VARCHAR2(3), 
        TOT_CRED NUMBER, 
        CONSTRAINT ID_PK PRIMARY KEY (ID), 
        CONSTRAINT TC_CHECK CHECK (TOT_CRED <= 180)
); 

INSERT INTO STUDENT VALUES (00128, 'Zhang', 'CSE', 102);
INSERT INTO STUDENT VALUES (12345, 'Shangkar', 'CSE', 32);
INSERT INTO STUDENT VALUES (19991, 'Brandt', 'HIS', 80);
INSERT INTO STUDENT VALUES (23121, 'Chavez', 'FIN', 110);
INSERT INTO STUDENT VALUES (44553, 'Peltier', 'PHY', 56);
INSERT INTO STUDENT VALUES (45678, 'Levy', 'PHY', 46);
INSERT INTO STUDENT VALUES (54321, 'Williams', 'CSE', 5);
INSERT INTO STUDENT VALUES (55739, 'Sanchez', 'MUS', 0);
INSERT INTO STUDENT VALUES (70557, 'Snow', 'PHY', 0);
INSERT INTO STUDENT VALUES (76543, 'Brown', 'CSE', 58);
INSERT INTO STUDENT VALUES (76653, 'Aoi', 'EEE', 60);
INSERT INTO STUDENT VALUES (98765, 'Bourikas', 'EEE', 9);
INSERT INTO STUDENT VALUES (98988, 'Tanaka' , 'BIO', 120);

SELECT * FROM STUDENT;

SELECT NAMEX, DEPT_NAME FROM STUDENT WHERE TOT_CRED >= 80 AND TOT_CRED <= 120; 
SELECT ID, NAMEX FROM STUDENT WHERE DEPT_NAME = 'CSE'; 
SELECT NAMEX, TOT_CRED FROM STUDENT WHERE DEPT_NAME = 'PHY' AND TOT_CRED < 50; 
SELECT DEPT_NAME FROM STUDENT WHERE NAMEX = 'Shangkar' OR NAMEX = 'Sanchez'; 

DELETE FROM STUDENT 
WHERE TOT_CRED < 10; 

-- Pending tasks: 


SELECT NAMEX, TOT_CRED 
FROM STUDENT 
WHERE TOT_CRED = (SELECT MAX(TOT_CRED) FROM STUDENT);

SELECT SUM(TOT_CRED) AS TOTAL_CREDITS 
FROM STUDENT 
WHERE DEPT_NAME = 'PHY';
