DROP TABLE VEHICLE; 
DROP TABLE OWNER; 

CREATE TABLE VEHICLE (
    VEHICLE_ID INT,
    MODEL VARCHAR2(50),
    MTYPE VARCHAR2(20),
    HORSEPOWER INT,
    TORQUE INT,
    WEIGHT INT,
    SPEED INT,
    CONSTRAINT VEHICLE_ID_PK PRIMARY KEY (VEHICLE_ID)
);
CREATE TABLE OWNER (
    OWNER_ID INT,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30),
    CITY VARCHAR2(30), 
    CONSTRAINT OWNER_ID_PK PRIMARY KEY (OWNER_ID) 
);
INSERT INTO VEHICLE VALUES
    (1, 'Toyota Corolla', 'Sedan', 132, 128, 2800, 112);
INSERT INTO VEHICLE VALUES
    (2, 'Honda Civic', 'Sedan', 158, 138, 2760, 125);
INSERT INTO VEHICLE VALUES
    (3, 'Ford Fusion', 'Sedan', 175, 175, 3431, 125);
INSERT INTO VEHICLE VALUES
    (4, 'Ford Mustang', 'Sports', 310, 350, 3532, 155);
INSERT INTO VEHICLE VALUES
    (5, 'Chevrolet Camaro', 'Sports', 275, 295, 3354, 155);
INSERT INTO VEHICLE VALUES
    (6, 'Dodge Challenger', 'Sports', 305, 268, 3894, 155);
INSERT INTO VEHICLE VALUES
    (7, 'Honda CR-V', 'SUV', 190, 179, 3337, 112);
INSERT INTO VEHICLE VALUES
    (8, 'Toyota RAV4', 'SUV', 203, 184, 3370, 114);
INSERT INTO VEHICLE VALUES
    (9, 'Ford Explorer', 'SUV', 300, 310, 4345, 143);
INSERT INTO VEHICLE VALUES
    (10, 'Tesla Model 3', 'Electric', 283, 307, 3554, 140);
INSERT INTO VEHICLE VALUES
    (11, 'Tesla Model S', 'Electric', 762, 723, 4647, 155);

INSERT INTO OWNER VALUES
    (1, 'John', 'Smith', 'New York');
INSERT INTO OWNER VALUES
    (2, 'Sarah', 'Johnson', 'Los Angeles');
INSERT INTO OWNER VALUES
    (3, 'Michael', 'Williams', 'Chicago');
INSERT INTO OWNER VALUES
    (4, 'Emily', 'Brown', 'New York');
INSERT INTO OWNER VALUES
    (5, 'David', 'Jones', 'Houston');

SELECT AVG (HORSEPOWER)
FROM VEHICLE; 

SELECT MTYPE, AVG_HORSEPOWER
FROM (
    SELECT MTYPE, AVG(HORSEPOWER) AS AVG_HORSEPOWER
    FROM VEHICLE
    GROUP BY MTYPE
    ORDER BY AVG_HORSEPOWER DESC
) 
WHERE ROWNUM = 1;

SELECT MTYPE
FROM (
    SELECT MTYPE, COUNT(*) AS CAR_COUNT
    FROM VEHICLE
    GROUP BY MTYPE
    ORDER BY CAR_COUNT DESC
)
WHERE ROWNUM = 1;


SELECT MODEL, MTYPE, WEIGHT
FROM VEHICLE
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM VEHICLE);

SELECT O.FIRST_NAME
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE V.MODEL LIKE 'Tesla%';

SELECT O.FIRST_NAME || ' ' || O.LAST_NAME || ' owns ' || V.MODEL AS OWNERSHIP
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID;

--Pending Tasks: 


SELECT MTYPE, AVG(TORQUE) AS AVG_TORQUE
FROM VEHICLE
GROUP BY MTYPE
HAVING AVG(TORQUE) > 250;

SELECT O.CITY
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE V.MTYPE IN ('Sedan', 'Sports')
GROUP BY O.CITY
HAVING COUNT(*) > 1;

SELECT MODEL, SPEED
FROM VEHICLE
WHERE MODEL LIKE 'Ford%'
ORDER BY SPEED DESC;

SELECT O.FIRST_NAME, O.LAST_NAME
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE V.SPEED = (SELECT MIN(SPEED) FROM VEHICLE);

SELECT MODEL, SPEED
FROM VEHICLE
WHERE MTYPE = 'SUV'
AND SPEED > (SELECT MAX(SPEED) FROM VEHICLE WHERE MTYPE = 'Sedan')
AND ROWNUM = 1;

SELECT DISTINCT O.FIRST_NAME, O.LAST_NAME
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE V.MTYPE = 'Electric';

SELECT O1.FIRST_NAME, O1.LAST_NAME, O2.FIRST_NAME, O2.LAST_NAME, V.MODEL
FROM OWNER O1
JOIN VEHICLE V ON O1.OWNER_ID = V.VEHICLE_ID
JOIN OWNER O2 ON O1.OWNER_ID != O2.OWNER_ID AND O2.OWNER_ID = V.VEHICLE_ID
ORDER BY V.MODEL;

SELECT O.FIRST_NAME, O.LAST_NAME, V.MODEL, V.SPEED
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE V.MTYPE = 'Sports'
AND V.SPEED = (SELECT MIN(SPEED) FROM VEHICLE WHERE MTYPE = 'Sports');

SELECT COUNT(*) AS TOTAL_VEHICLES
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
WHERE O.CITY = 'New York';

SELECT O.FIRST_NAME, O.LAST_NAME
FROM OWNER O
JOIN VEHICLE V ON O.OWNER_ID = V.VEHICLE_ID
GROUP BY O.FIRST_NAME, O.LAST_NAME
HAVING COUNT(V.VEHICLE_ID) > (SELECT AVG(VEHICLE_COUNT) 
                              FROM (SELECT COUNT(*) AS VEHICLE_COUNT 
                                    FROM VEHICLE 
                                    GROUP BY VEHICLE_ID));
